<div class="row">
    <div class="col-lg-10 col-lg-offset-1">

        <h3>Controller</h3>
        <table class="table table-striped table-condensed">
            <tr>  
                <th class="text-right">STATUS</th> <td><?php echo ($controllerGenerator->getStatus()) ? "<label class='text-success'>OK</label>" : "<label class='text-danger'>Fail</label>"; ?></td>
            </tr>
            <tr>  
                <th class="text-right">FILE EXISTS</th> <td><?php echo ($controllerGenerator->getExists()) ? "YES" : "NO"; ?></td>
            </tr> 
            <tr>  
                <th class="text-right">MSJ</th> <td><?php echo $controllerGenerator->getMsj(); ?></td>
            </tr>
            <tr>
                <th class="text-right">RELATIVE PATH</th> <td><?php echo $controllerGenerator->getPath(); ?></td>
            </tr>
            <tr>  
                <th class="text-right">COMPLETE PATH</th> <td><?php echo $controllerGenerator->getCompletePath(); ?></td>
            </tr>
            <tr>  
                <th class="text-right">FILE NAME</th> <td><?php echo $controllerGenerator->getName(); ?></td>
            </tr>

            <tr>  
                <th class="text-right">PATH & FILE NAME</th> <td><?php echo $controllerGenerator->getFileName(); ?></td>
            </tr>
        </table>
        
        <h3>Controller Factory</h3>
        <table class="table table-striped table-condensed">
            <tr>  
                <th class="text-right">STATUS</th> <td><?php echo ($controllerFactoryGenerator->getStatus()) ? "<label class='text-success'>OK</label>" : "<label class='text-danger'>Fail</label>"; ?></td>
            </tr>
            <tr>  
                <th class="text-right">FILE EXISTS</th> <td><?php echo ($controllerFactoryGenerator->getExists()) ? "YES" : "NO"; ?></td>
            </tr> 
            <tr>  
                <th class="text-right">MSJ</th> <td><?php echo $controllerFactoryGenerator->getMsj(); ?></td>
            </tr>
            <tr>
                <th class="text-right">RELATIVE PATH</th> <td><?php echo $controllerFactoryGenerator->getPath(); ?></td>
            </tr>
            <tr>  
                <th class="text-right">COMPLETE PATH</th> <td><?php echo $controllerFactoryGenerator->getCompletePath(); ?></td>
            </tr>
            <tr>  
                <th class="text-right">FILE NAME</th> <td><?php echo $controllerFactoryGenerator->getName(); ?></td>
            </tr>

            <tr>  
                <th class="text-right">PATH & FILE NAME</th> <td><?php echo $controllerFactoryGenerator->getFileName(); ?></td>
            </tr>
        </table>   


    </div>

</div>