<nav class="navbar navbar-default navbar-fixed-top navbar-inverse" >
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">TEMPLATE</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            <?php
            echo $this->renderMenu();
            ?>

            <ul class="nav navbar-nav navbar-right">
                <?php echo $this->partial('zf-metal/security/menu/menu'); ?> 
            </ul>

        </div>


    </div>
</nav>
