<div class="row">
    <div class="col-12">


        <div class="panel panel panel-primary">
            <div class="panel-heading">
                <h4 class="panel-title"><?php echo $this->translate('Gestion de Modulos'); ?></h4>     
            </div>
            <div class="panel-body">

                <?php echo $this->Grid($this->grid); ?>

            </div>
        </div>
    </div>
</div>
