<br>
<div class="">
    <h3 class="text-center">Module: <?php echo $this->module->getName(); ?></h3>

</div>
<br>
<div class="clearfix"></div>

<div class="">
    <ul>
        <li>
            <button id="btn-generate-module" class="btn btn-primary btn-xs btn-circle">Generate</button>
            Module.php
        </li>
        <li>
            <button id="btn-generate-module-config" class="btn btn-success btn-xs">Generate</button>
            module.config.php  
        </li>
        <li>
            Agregate module to composer.json (Autoload PSR4).
        </li>
        <li>
            Exec command "composer dump-autoload".
        </li>
    </ul>

</div>