<br>
<div class="">
    <h3 class="text-center">Module: <?php echo $this->module->getName(); ?></h3>

</div>
<br>
<div class="clearfix"></div>

<div>
    <p>To enable the module, you need to perform the following steps:</p>
    <br>
</div>

<div class="">
    <ul>
        <li>
            <button id="btn-generate-module" class="btn btn-primary btn-xs btn-circle">Generate</button>
            Module.php
        </li>
        <br>
        <li>
            <button id="btn-generate-module-config" class="btn btn-success btn-xs">Generate</button>
            module.config.php  
        </li>

        <br>
        <li>
            <button id="btn-generate-module-composer" class="btn btn-warning btn-xs">Aggregate</button>
            Aggregate module to composer.json (Autoload PSR4).
            <br> <br>
            <div>
                <pre>
                "autoload": {
                    "psr-4": {
                        "<?php echo $this->module->getName(); ?>\\": "module/<?php echo $this->module->getName(); ?>/src/"
                    }
                },   
                </pre>
            </div>
        </li>
        <br>
        <li>
               <button id="btn-generate-module-dump-autoload" class="btn btn-danger btn-xs">Execute</button>
         
            Execute command: "composer dump-autoload"  (need permissions)
 
        </li>
        <br>
        <li>
            <strong>MANUAL STEP! (for now)</strong> Agregate Module to proyect modules.config.php
      </li>
 
    </ul>

</div>


 <a href="<?php echo $this->url("ZfMetal_Generator/Module/Delete",["moduleId" => $this->module->getId()]); ?>" id="btn-generate-module-delete" class="btn btn-default btn-xs pull-right">Delete Module</a>
           