<?php
//ZfMetal\View\Helper\BootstrapModal
// ObjectJavascript = MetalModal
$this->bootstrapModal('metalModal', true, 'modal-lg');

//ADD route,crontroller,entity  Javascript Class
$this->headScript()
        ->appendScript($this->partial('zf-metal/generator/route/js/route.js'), 'text/javascript')
        ->appendScript($this->partial('zf-metal/generator/controller/js/controller.js'), 'text/javascript')
        ->appendScript($this->partial('zf-metal/generator/entity/js/entity.js'), 'text/javascript');
?>    

<script type='text/javascript'>
    var MetalRoutes;
    var MetalControllers;
    var MetalEntities;
    jQuery(function ($) {
        //Routes
        MetalRoutes = new $.MetalRoutes();
        MetalRoutes.setModal(MetalModal);
        MetalRoutes.run(<?php echo $module->getId(); ?>);
        //Controllers
        MetalControllers = new $.MetalControllers();
        MetalControllers.setModal(MetalModal);
        MetalControllers.run(<?php echo $module->getId(); ?>);
        //Entities
        MetalEntities = new $.MetalEntities();
        MetalEntities.setModal(MetalModal);
        MetalEntities.run(<?php echo $module->getId(); ?>);

    });
</script>


<style>

    .fade {
        opacity: 0;
        -webkit-transition: opacity 0.15s linear;
        -moz-transition: opacity 0.15s linear;
        -ms-transition: opacity 0.15s linear;
        -o-transition: opacity 0.15s linear;
        transition: opacity 0.15s linear;
    }

    .section-header{
        padding-bottom: 6px;
        margin: 20px 0 10px;
        border-bottom: 1px solid #eee;
    }

</style>