<div class="row">
    <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <?php echo $this->translate('Modules'); ?>
                <span class="pull-right">
                    <a href="<?php echo $this->url("ZfMetal_Generator/Module/Create"); ?>" class="btn btn-xs btn-primary glyphicon glyphicon-plus"></a>
                </span>


            </div>
            <div class="panel-body">
                <div class="list-group">

                    <?php foreach ($this->modules as $m): ?>

                        <a href="<?php echo $this->url("ZfMetal_Generator/Main", ['moduleId' => $m->getId()]); ?>" class="list-group-item">
                            <i class="fa fa-comment fa-fw"></i> <?php echo $m->getName(); ?>
                            </span>
                        </a>

                    <?php endforeach; ?>

                </div>
            </div>

        </div>

    </div>
    <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
        <?php if ($this->module): ?>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title"> <?php echo $this->translate('Module'); ?>: <strong><?php echo $module->getName(); ?></strong></h4>
                </div>
                <div class="panel-body">

                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#entityTab" data-toggle="tab" aria-expanded="true">Entity</a>
                        </li>
                        <li class=""><a href="#controllerTab" data-toggle="tab" aria-expanded="false">Controller</a>
                        </li>
                        <li class=""><a href="#routeTab" data-toggle="tab" aria-expanded="false">Routes</a>
                        </li>
                        <li class=""><a href="#navigationTab" data-toggle="tab" aria-expanded="false">Navigation</a>
                        </li>
                        <li class=""><a href="#optionTab" data-toggle="tab" aria-expanded="true">Options</a>
                        </li>
                        <li class=""><a href="#pluginControllerTab" data-toggle="tab" aria-expanded="false">Plugin Controller</a>
                        </li>
                        <li class=""><a href="#viewHelperTab" data-toggle="tab" aria-expanded="false">View Helper</a>
                        </li>
                        <li class=""><a href="#formTab" data-toggle="tab" aria-expanded="false">Forms</a>
                        </li>
                    </ul>

                    <div class="tab-content">
                        <div class="tab-pane fade active in" id="entityTab">

                            <h4>Entity</h4>
                            <br>
                            <i class="glyphicon glyphicon-transfer"> Cargando...</i>

                        </div>
                        <div class="tab-pane fade" id="controllerTab">
                            <h4>Controllers</h4>
                            <br>
                            <i class="glyphicon glyphicon-transfer"> Cargando...</i>

                        </div>
                        <div class="tab-pane fade" id="routeTab">

                            <?php echo $this->partial("zf-metal/generator/route/route-tab"); ?>


                        </div>
                        <div class="tab-pane fade" id="navigationTab">
                            <?php echo $this->partial("zf-metal/generator/navigation/navigation-tab"); ?>

                        </div>
                        <div class="tab-pane fade" id="optionTab">
                            <h4 class="section-header">Options <button class="btn btn-primary" id="btn-generate-option">Generate</button></h4>
                            <div id="optionContent">
                                
                            </div>
                        </div>

                        <div class="tab-pane fade" id="pluginControllerTab">
                            <h4 class="section-header">Plugin Generate <button class="btn btn-primary" id="btn-generate-plugin">Generate</button></h4>
                            <div id="pluginContent">
                                
                            </div>
                        </div>

                        <div class="tab-pane fade" id="viewHelperTab">
                            <h4 class="section-header">ViewHelper Generate <button class="btn btn-primary" id="btn-generate-view-helper">Generate</button></h4>
                            <div id="viewHelperContent"></div>
                        </div>

                        <div class="tab-pane fade" id="formTab">
                            <h4>Forms</h4>
                            <p></p>
                        </div>
                    </div>

                </div>

            </div>

        <?php endif; ?>
    </div>
</div>

<?php
//ADD TREEVIEW JQUERY
$this->headScript()->appendFile('/shared/bootstrap-treeview/bootstrap-treeview.min.js', 'text/javascript');
$this->headLink()->appendStylesheet($this->basePath() . '/shared/bootstrap-treeview/bootstrap-treeview.min.css');
?>


<?php if ($this->module): ?>
    <?php echo $this->partial("zf-metal/generator/main/assets"); ?>
<?php endif; ?>
