<div class="row">

        <div class="col-lg-6 col-md-6 ">
        <h3>Controller</h3>
        <?php echo $this->partial('zf-metal/generator/generator/base-result', ["fileGenerator" => $controllerGenerator]); ?>
        </div>
        
        <div class="col-lg-6 col-md-6">
        <h3>Controller Factory</h3>
        <?php echo $this->partial('zf-metal/generator/generator/base-result', ["fileGenerator" => $controllerFactoryGenerator]); ?>
        </div>


</div>