<div class="row">
    <div class="col-lg-10 col-lg-offset-1">

        
         <div class="col-lg-6 col-md-6 ">
        <h3>Entity</h3>
        <?php echo $this->partial('zf-metal/generator/generator/base-result', ["fileGenerator" => $entityGenerator]); ?>
        </div>
        
          <div class="col-lg-6 col-md-6 ">
        <h3>Entity Repository</h3>
        <?php echo $this->partial('zf-metal/generator/generator/base-result', ["fileGenerator" => $repositoryGenerator]); ?>
        </div>

    </div>

</div>