<div class="row">

    <div class="col-lg-6 col-md-6 ">
        <h3>optionGenerator</h3>
        <?php echo $this->partial('zf-metal/generator/generator/base-result', ["fileGenerator" => $optionGenerator]); ?>
    </div>
    
    <div class="col-lg-6 col-md-6 ">
        <h3>optionFactoryGenerator</h3>
        <?php echo $this->partial('zf-metal/generator/generator/base-result', ["fileGenerator" => $optionFactoryGenerator]); ?>
    </div>
</div>