<div class="row">
    <div class="col-lg-6 col-md-6 ">
        <h3>Plugin Generator</h3>
        <?php echo $this->partial('zf-metal/generator/generator/base-result', ["fileGenerator" => $pluginGenerator]); ?>
    </div>
    <?php if ($pluginFactoryGenerator):?>
    <div class="col-lg-6 col-md-6 ">
        <h3>Plugin Factory Generator</h3>
        <?php echo $this->partial('zf-metal/generator/generator/base-result', ["fileGenerator" => $pluginFactoryGenerator]); ?>
    </div>
    <?php endif;?>
</div>