<div class="row">
    <div class="col-lg-6 col-md-6 ">
        <h3>ViewHelper Generator</h3>
        <?php echo $this->partial('zf-metal/generator/generator/base-result', ["fileGenerator" => $viewHelperGenerator]); ?>
    </div>
    <?php if ($viewHelperFactoryGenerator):?>
    <div class="col-lg-6 col-md-6 ">
        <h3>Plugin Factory Generator</h3>
        <?php echo $this->partial('zf-metal/generator/generator/base-result', ["fileGenerator" => $viewHelperFactoryGenerator]); ?>
    </div>
    <?php endif;?>
</div>