<?php echo $this->flashCurrent(); ?>
<div class="row">
    <div class="col-lg-offset-2 col-lg-8 col-md-offset-2 col-md-8 col-sm-12 col-xs-12">
        <?php
        
          $groups = [
            [
                'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_VERTICAL,
                'id' => 'Main',
                'title' => 'Main',
                'columns' => \ZfMetal\Commons\Consts::COLUMNS_TWO,
                'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                'fields' => ['name', 'type', 'mayTerminate']
            ],
            [
                'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_VERTICAL,
                'id' => 'Options',
                'title' => 'Options',
                'columns' => \ZfMetal\Commons\Consts::COLUMNS_TWO,
                'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                'fields' => ['route', 'controller', 'action']
            ],
        ];
        
        echo $this->renderForm($this->form,\ZfMetal\Commons\Consts::STYLE_VERTICAL,\ZfMetal\Commons\Consts::COLUMNS_TWO,$groups);
        ?>
    </div>
</div>


<?php echo $this->JQSelectPopulate("/generator/module/action/json-by-controller","controller","action"); ?>