<?php echo $this->flashCurrent(); ?>

<div class="row">
<div class="col-lg-offset-2 col-lg-8 col-md-offset-2 col-md-8 col-sm-12 col-xs-12">
    <?php
        $verticalGroups = [
            'Main' =>['name','type','mayTerminate'],
            'Options' =>['route','controller','action'],
        ];
        
    
    echo $this->renderForm($this->form,\ZfMetal\Commons\Consts::STYLE_VERTICAL,\ZfMetal\Commons\Consts::COLUMNS_TWO,null,$verticalGroups);
    ?>
</div>
</div>
<?php echo $this->JQSelectPopulate("/generator/module/action/json-by-controller","controller","action",$this->form->getObject()->getId()); ?>