
<div class="form-group">
    <label for="input-search" class="sr-only">Search Route:</label>
    <input type="input" class="form-control" id="input-search-nav" placeholder="Type to search..." value="">
</div>
<div class="checkbox">
    <label>
        <input type="checkbox" class="checkbox" id="chk-exact-match-nav" value="false">
        Exact Match
    </label>
</div>
<div class="checkbox">
    <label>
        <input type="checkbox" class="checkbox" id="chk-ignore-case-nav" value="true">
        Ignore Case
    </label>
</div>

<div class="checkbox">
    <label>
        <input type="checkbox" class="checkbox" id="chk-reveal-results-nav" value="true">
        Reveal Results
    </label>
</div>
<button type="button" class="btn btn-success" id="btn-search-nav">Search</button>
<button type="button" class="btn btn-default" id="btn-clear-search-nav">Clear</button>
<!-- </form> -->
