<span>Menu Name: </span>
<span id="nav-selected-label" style="color: #333333;"></span>

<br>
<span>Menu URL: </span>
<span id="nav-selected-uri" style="color: #333333;"></span>
<br><br>
<button type="button" class="btn btn-success" id="btn-add-nav" >Add</button>
<button type="button" class="btn btn-primary" id="btn-edit-nav">Edit</button>
<button type="button" class="btn btn-danger" id="btn-del-nav" >Del</button>
<button type="button" class="btn btn-warning" id="btn-clear-nav">Clear</button>
<button type="button" class="btn btn-default glyphicon glyphicon-collapse-up" id="btn-clear-collapse-nav"></button>
<button type="button" class="btn btn-default glyphicon glyphicon-collapse-down" id="btn-clear-expand-nav"></button>
<!-- </form> -->
