<?php echo $this->Grid($this->grid); ?>
<script type="text/javascript">
    function changetype() {
        var types = $("[name='type'").val();

        if (types == "file") {
            $("#form-group-File").show();
            $("[name='absolutepath']").parent().parent().show();
            $("[name='webpath']").parent().parent().show();
        } else {
            $("#form-group-File").hide();
            $("[name='absolutepath']").parent().parent().hide();
            $("[name='webpath']").parent().parent().hide();
        }

        if (types == "oneToOne" || types == "manyToOne" || types == "oneToMany") {
            $("[name='length']").parent().parent().hide();
            $("[name='relatedEntity']").parent().parent().show();
        } else {

            $("[name='length']").parent().parent().show();
            $("[name='relatedEntity']").parent().parent().hide();
        }

    }

    changetype();

</script>

