<?php echo $this->Grid($this->grid); ?>
<script type="text/javascript">
    function changetype(element) {
        if (element) {
            types = $(element).val();
        } else {
            types = null;
        }
        if (types == "file") {
            $("#form-group-File").show();
            $("[name='absolutepath']").parent().show();
            $("[name='webpath']").parent().show();
        } else {
            $("#form-group-File").hide();
            $("[name='absolutepath']").parent().hide();
            $("[name='webpath']").parent().hide();
        }

        if (types == "boolean" || types == "date" || types == "datetime" || types == "time" || types == "text") {
            $("[name='length']").parent().hide();
        } else if (types == "oneToOne" || types == "manyToOne" || types == "oneToMany" || types == "manyToMany") {
            $("[name='length']").parent().hide();
            $("[name='relatedEntity']").parent().show();
            if (types == "oneToOne") {
                $("[name='mappedBy']").parent().show();
            }

        } else {

            $("[name='length']").parent().show();
            $("[name='relatedEntity']").parent().hide();
            $("[name='mappedBy']").parent().hide();
        }

    }

    changetype(null);

</script>

