<?php echo $this->flashCurrent(); ?>

<div class="row">
<div class="col-lg-offset-2 col-lg-8 col-md-offset-2 col-md-8 col-sm-12 col-xs-12">
    <?php
    echo $this->renderForm($this->form, \ZfMetal\Commons\Consts::STYLE_HORIZONTAL,\ZfMetal\Commons\Consts::COLUMNS_TWO);
    ?>
</div>
</div>

<script>
    function submitCommons() {
        $.post('/generator/module/controller/commons/<?php echo $this->controllerId; ?>',
                $('#ControllerCommons').serialize(),
                function (data) {
                    $("#modalContent").html(data);
                });
    }
</script>