<?php

return [
    'zf-metal-datagrid.custom' => [
        "ZfMetal\Generator\Entity\Property" => [
            "sourceConfig" => [
                "type" => "doctrine",
                "doctrineOptions" => [
                    "entityName" => "\ZfMetal\Generator\Entity\Property",
                    "entityManager" => "doctrine.entitymanager.orm_zf_metal_generator"
                ]
            ],
            "formConfig" => [
                'columns' => \ZfMetal\Commons\Consts::COLUMNS_TWO,
                'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                'groups' => [
                    [
                        'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_VERTICAL,
                        'id' => 'DB',
                        'title' => 'DB',
                        'columns' => \ZfMetal\Commons\Consts::COLUMNS_TWO,
                        'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                        'fields' => ['name', 'type', 'length', 'beUnique', 'beNullable', 'primarykey', 'autoGeneratedValue', 'relatedEntity','mappedBy', 'createdAt', 'updatedAt']
                    ],
                    [
                        'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_VERTICAL,
                        'id' => 'File',
                        'title' => 'File',
                        'columns' => \ZfMetal\Commons\Consts::COLUMNS_TWO,
                        'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                        'fields' => ['webpath', 'absolutepath']
                    ],
                    [
                        'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_VERTICAL,
                        'id' => 'Form',
                        'title' => 'Form',
                        'columns' => \ZfMetal\Commons\Consts::COLUMNS_TWO,
                        'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                        'fields' => ['label', 'addon', 'description', 'elementType', 'exclude', 'hidden', 'mandatory', 'tostring']
                    ],
                    [
                        'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_VERTICAL,
                        'id' => 'Datagrid',
                        'title' => 'Datagrid',
                        'columns' => \ZfMetal\Commons\Consts::COLUMNS_TWO,
                        'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                        'fields' => ['hiddenDatagrid']
                    ],
                ]
            ],
            "columnsConfig" => [
                "createdAt" => [
                    "hidden" => true,
                ],
                "updatedAt" => [
                    "hidden" => true,
                ],
                "elementType" => [
                    "hidden" => true
                ],
                "addon" => [
                    "hidden" => true
                ],
                "absolutepath" => [
                    "hidden" => true
                ],
                "webpath" => [
                    "hidden" => true
                ],
                "description" => [
                    "hidden" => true
                ],
                "label" => [
                    "hidden" => true
                ],
                "exclude" => [
                    "hidden" => true
                ],
                "entity" => [
                    "hidden" => true
                ],
                "beNullable" => [
                    "displayName" => "Null",
                ],
                "beUnique" => [
                    "displayName" => "Unique",
                ],
                "hidden" => [
                    "hidden" => true
                ],
                "hiddenDatagrid" => [
                    "hidden" => true
                ],
                "mandatory" => [
                    "hidden" => true
                ],
                "tostring" => [
                    "hidden" => true
                ],
                "primarykey" => [
                    "hidden" => true
                ], "autoincrement" => [
                    "hidden" => true
                ],
            ],
            "crudConfig" => [
                "enable" => true,
                "add" => [
                    "enable" => true,
                ],
                "edit" => [
                    "enable" => true,
                ],
                "del" => [
                    "enable" => true,
                ],
                "view" => [
                    "enable" => true,
                ],
            ],
        ],
    ]
];

