<div id="router-search" class="col-md-4">
    <h3 class="section-header">ABM</h3>
   
    <?php echo $this->partial("zf-metal/generator/navigation/partial/nav-abm", ['moduleId' => $this->module->getId()]); ?>

    <h3 class="section-header">Search</h3>
    
    <?php echo $this->partial("zf-metal/generator/navigation/partial/nav-search"); ?>

</div>

<div  class="col-md-6 col-md-offset-1">
    <h3 class="section-header">Navigation <button class="btn btn-primary" id="btn-generate-routes">Generate</button></h4>
    <div id="nav-tree-content">
        <br>
        <i class="glyphicon glyphicon-transfer"> Cargando...</i>

    </div>


</div>
