<span>Route Name: </span>
<span id="route-selected-parent_route_name" style="color: #333333;"></span><span id="route-selected-route_name" style="color: #456785;font-weight: bold;"></span>
<br>
<span>Route URL: </span>
<span id="route-selected-parent_route_url" style="color: #333333;"></span><span id="route-selected-route_url" style="color: #456785;font-weight: bold;"></span>
<br><br>
<button type="button" class="btn btn-success" id="btn-add-route" >Add</button>
<button type="button" class="btn btn-primary" id="btn-edit-route">Edit</button>
<button type="button" class="btn btn-danger" id="btn-del-route" >Del</button>
<button type="button" class="btn btn-warning" id="btn-clear-route">Clear</button>
<button type="button" class="btn btn-default glyphicon glyphicon-collapse-up" id="btn-clear-collapse"></button>
<button type="button" class="btn btn-default glyphicon glyphicon-collapse-down" id="btn-clear-expand"></button>
<!-- </form> -->
