
<div class="form-group">
    <label for="input-search" class="sr-only">Search Route:</label>
    <input type="input" class="form-control" id="input-search" placeholder="Type to search..." value="">
</div>
<div class="checkbox">
    <label>
        <input type="checkbox" class="checkbox" id="chk-exact-match" value="false">
        Exact Match
    </label>
</div>
<div class="checkbox">
    <label>
        <input type="checkbox" class="checkbox" id="chk-ignore-case" value="true">
        Ignore Case
    </label>
</div>

<div class="checkbox">
    <label>
        <input type="checkbox" class="checkbox" id="chk-reveal-results" value="true">
        Reveal Results
    </label>
</div>
<button type="button" class="btn btn-success" id="btn-search">Search</button>
<button type="button" class="btn btn-default" id="btn-clear-search">Clear</button>
<!-- </form> -->
